package net.liuzd.mybatis.mapper;

import java.util.List;
import net.liuzd.mybatis.model.SysUser;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);
    
    /**
    * 根据对象的主键删除
    *
    * @param sysUser
    * @return
    */
    int deleteBySysUser(SysUser sysUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    SysUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    List<SysUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysUser record);
    
    /**
     * 新增用户-使用useGeneratedKeys方式     *
     * @param sysUser
     * @return
     */
    int insertUseGeneratedKeys(SysUser sysUser);
    
    /**
     * 新增用户-使用selectKey方式
     *
     * @param sysUser
     * @return
     */
    int insertUseSelectKey(SysUser sysUser);
}